// Auto-generated by scripts/generate-script-api-types.mjs — do not edit.

export const indexDts = `/// <reference path="./plugin-app-api.d.ts" />
/// <reference path="./trigger-data.d.ts" />

/** One trigger payload passed to script handlers. */
type HandlerTriggerContext = {
	/** Stable trigger definition ID (for example \`twitch:twitch:chat:chat-message\`). */
	trigger: string;
	/** Trigger-specific payload. Narrowed in the editor when action triggers are known. */
	data: TriggerDataUnion;
	/** Mutable action-scoped variables for the current handler chain run. */
	actionVariables?: Record<string, string>;
};

/** Arguments passed to Run script handler user code. */
type ScriptContext = {
	/** Full Stream Kit application API (same as plugin handlers). */
	app: PluginAppApi;
	/** Trigger contexts for this action run (usually one entry). */
	context: HandlerTriggerContext[];
};

/** Return value of a Run script handler body. */
type ScriptResult = void | Promise<void>;

/** A Run script handler body with fully typed \`app\` and \`context\`. */
type ScriptHandler = (ctx: ScriptContext) => ScriptResult;

/**
 * Entry point for a Run script action. Return your handler from \`defineScript\`
 * to get full autocomplete and type checking, then \`export default\` it.
 *
 * Your handler receives:
 * - \`app\` — the Stream Kit API: \`app.toast\`, \`app.fs\`, \`app.plugins\`,
 *   \`app.actions\`, \`app.process\`, and more.
 * - \`context\` — the triggers that fired this action. Each entry has \`trigger\`
 *   (the trigger ID), \`data\` (the trigger payload, typed to this action's
 *   triggers), and \`actionVariables\` (mutable variables shared with later handlers).
 *
 * @example
 * export default defineScript(async ({ app, context }) => {
 * 	const [{ trigger, data, actionVariables }] = context;
 * 	app.toast.create({ title: 'Hello!', variant: 'success' });
 * });
 */
declare function defineScript(handler: ScriptHandler): ScriptHandler;
`;
export const pluginAppApiDts = `/// <reference path="./trigger-data.d.ts" />
/// <reference path="./index.d.ts" />

declare const BaseDirectory: {
	readonly Audio: 1;
	readonly Cache: 2;
	readonly Config: 3;
	readonly Data: 4;
	readonly LocalData: 5;
	readonly Document: 6;
	readonly Download: 7;
	readonly Picture: 8;
	readonly Public: 9;
	readonly Video: 10;
	readonly Resource: 11;
	readonly Temp: 12;
	readonly AppConfig: 13;
	readonly AppData: 14;
	readonly AppLocalData: 15;
	readonly AppCache: 16;
	readonly AppLog: 17;
	readonly Desktop: 18;
	readonly Executable: 19;
	readonly Font: 20;
	readonly Home: 21;
	readonly Runtime: 22;
	readonly Template: 23;
};
type BaseDirectory = (typeof BaseDirectory)[keyof typeof BaseDirectory];

declare const SeekMode: { readonly Start: 0; readonly Current: 1; readonly End: 2 };
type SeekMode = (typeof SeekMode)[keyof typeof SeekMode];

type UnlistenFn = () => void;
type UnwatchFn = () => void;
type TranslationKey = string;
type HandlerDefinition = unknown;
type PluginSettingsContext = unknown;
type PluginMigration = unknown;
type SettingsFieldValue = string | number | boolean;
type ConfirmOptions = { title?: string; description?: string; confirmLabel?: string; cancelLabel?: string; variant?: string };
type FileSystemFilter = { name: string; extensions: string[] };
type FileSystemSelectOptions = { type: 'file' | 'folder'; filters?: FileSystemFilter[] };
type CreateOptions = { baseDir?: BaseDirectory };
type OpenOptions = { read?: boolean; write?: boolean; append?: boolean; truncate?: boolean; create?: boolean; createNew?: boolean; mode?: number; baseDir?: BaseDirectory };
type CopyFileOptions = { fromPathBaseDir?: BaseDirectory; toPathBaseDir?: BaseDirectory };
type MkdirOptions = { mode?: number; recursive?: boolean; baseDir?: BaseDirectory };
type ReadDirOptions = { baseDir?: BaseDirectory };
type ReadFileOptions = { baseDir?: BaseDirectory; encoding?: string };
type RemoveOptions = { recursive?: boolean; baseDir?: BaseDirectory };
type RenameOptions = { oldPathBaseDir?: BaseDirectory; newPathBaseDir?: BaseDirectory };
type StatOptions = { baseDir?: BaseDirectory };
type TruncateOptions = { baseDir?: BaseDirectory };
type WriteFileOptions = { append?: boolean; create?: boolean; createNew?: boolean; mode?: number; baseDir?: BaseDirectory };
type WatchOptions = { recursive?: boolean; baseDir?: BaseDirectory };
type DebouncedWatchOptions = WatchOptions & { delayMs?: number };
type ExistsOptions = { baseDir?: BaseDirectory };
type WatchEventKindAccess = { kind: 'any' } | { kind: 'close'; mode: 'any' | 'execute' | 'read' | 'write' | 'other' } | { kind: 'open'; mode: 'any' | 'execute' | 'read' | 'write' | 'other' } | { kind: 'other' };
type WatchEventKindCreate = { kind: 'any' } | { kind: 'file' } | { kind: 'folder' } | { kind: 'other' };
type WatchEventKindModify = { kind: 'any' } | { kind: 'data'; mode: 'any' | 'size' | 'content' | 'other' } | { kind: 'metadata'; mode: 'any' | 'access-time' | 'write-time' | 'permissions' | 'ownership' | 'extended' | 'other' } | { kind: 'rename'; mode: 'any' | 'to' | 'from' | 'both' | 'other' } | { kind: 'other' };
type WatchEventKindRemove = { kind: 'any' } | { kind: 'file' } | { kind: 'folder' } | { kind: 'other' };
type WatchEventKind = 'any' | { access: WatchEventKindAccess } | { create: WatchEventKindCreate } | { modify: WatchEventKindModify } | { remove: WatchEventKindRemove } | 'other';
type WatchEvent = { type: WatchEventKind; paths: string[]; attrs: unknown };
type DirEntry = { name: string; isDirectory: boolean; isFile: boolean; isSymlink: boolean };
type FileInfo = { isFile: boolean; isDirectory: boolean; isSymlink: boolean; size: number; mtime: Date | null; atime: Date | null; birthtime: Date | null; readonly: boolean; fileAttributes: number | null; dev: number | null; ino: number | null; mode: number | null; nlink: number | null; uid: number | null; gid: number | null; rdev: number | null; blksize: number | null; blocks: number | null };
type FileHandle = { read(buffer: Uint8Array): Promise<number | null>; seek(offset: number, whence: SeekMode): Promise<number>; stat(): Promise<FileInfo>; truncate(len?: number): Promise<void>; write(data: Uint8Array): Promise<number>; close(): Promise<void> };
type MenuItemChild = { path: string; title?: TranslationKey | string; isDisabled?: boolean | (() => boolean); onClick?: () => void };
type MenuItemLink = { kind?: 'item'; path: string; title?: TranslationKey | string; icon: string; children?: MenuItemChild[]; isGroupOnly?: boolean; isDisabled?: boolean | (() => boolean); onClick?: () => void; fromPlugin?: boolean };
type Modal = { id: string; title: string; size: "sm" | "md" | "lg" | "full"; description?: string; content: unknown; props: Record<string, unknown>; contentHost: "app" | "plugin"; onClose?: () => void; isOpen: boolean; open(): void; close(): void };
type ModalProps = { id: string; title: string; description?: string; size?: "sm" | "md" | "lg" | "full"; content: unknown; props?: Record<string, unknown>; contentHost?: "app" | "plugin"; onClose?: () => void };
type OAuthStartOptions = { ports?: number[]; response?: unknown };
type ToastVariant = 'default' | 'success' | 'error' | 'warning';
type ToastCreateProps = { id?: string; title: string; description?: string; variant?: ToastVariant; duration?: number; content?: unknown; props?: Record<string, unknown> };
type ToastItem = { id: string; title: string; description?: string; variant: ToastVariant; duration?: number };
type CommandRecord = { id: string; name: string; group: string; groupSortOrder: number; sortOrder: number; commandNames: string[]; handlers: unknown[]; sources: unknown[]; permissions: unknown; cooldownGlobalMs: number | null; cooldownUserMs: number | null; enabled: boolean };
type RunProgramOptions = { command: string; workingDirectory?: string; arguments?: string; waitSeconds?: number; environment?: Record<string, string>; hideWindow?: boolean; useShell?: boolean };
type RunProgramResult = { exitCode: number | null; stdout: string; stderr: string; outputLines: string[] };
type LocalTtsRuntimeInfo = { installed: boolean };
type LocalTtsVoiceInfo = { id: string; name: string; language: string; quality: string; installed: boolean };
type ActionQueueDefinition = { id: number; name: string; concurrency: number; maxLength: number | null; sortOrder: number };
type ActionQueueEvent = 'paused' | 'resumed' | 'idle' | 'job_enqueued' | 'job_started' | 'job_completed';
type ActionQueueJobContext = { jobId: string; actionId: number | null; actionName: string };
type ActionQueueEventContext = { queueId: number; queueName: string; pending: number; active: number; paused: boolean; job?: ActionQueueJobContext };
type QueuedActionEntry = { jobId: string; actionId: number | null; actionName: string };
type ActionQueueStats = { pending: number; active: number; paused: boolean; pendingActions: QueuedActionEntry[]; activeActions: QueuedActionEntry[] };
type HotkeyEventContext = { shortcut: string; modifiers: string[]; key: string };
type ToolbarMetaItem = { icon?: string; label: string };
type ToolbarAction = { id: string; label: string; icon?: string; variant?: 'default' | 'outline' | 'destructive' | 'ghost'; size?: 'default' | 'sm' | 'lg' | 'xs'; disabled?: boolean; onClick: () => void | Promise<void> };
type ToolbarComponent = { id: string; component: unknown; props?: Record<string, unknown> };
type ToolbarSelectAll = { label: string; checked: boolean; onChange: (checked: boolean) => void };
type ToolbarConfig = { meta?: ToolbarMetaItem[]; primaryActions?: ToolbarAction[]; primaryComponents?: ToolbarComponent[]; selectAll?: ToolbarSelectAll | null; actions?: ToolbarAction[] };

/** Opaque Drizzle client returned by {@link PluginAppDbApi.getClient}. */
type PluginDbClient = unknown;

/**
 * Factory registered by the Commands plugin to activate chat command handling.
 * Called when the commands plugin boots or is enabled.
 */
type CommandRuntimeFactory = (app: PluginAppApi) => () => void;

/**
 * Global keyboard shortcuts registered through the Tauri global-shortcut plugin.
 */
interface PluginAppHotkeysApi {
	/** Register a global shortcut listener. Returns an unsubscribe function. */
	register(shortcut: string, handler: (context: HotkeyEventContext) => void): () => void;

	/** Whether the shortcut is registered by this application. */
	isRegistered(shortcut: string): Promise<boolean>;

	/** Invoke listeners registered for this shortcut (same as a physical key press). */
	trigger(shortcut: string): boolean;
}

/**
 * Action queue runtime and control APIs.
 */
interface PluginAppActionQueuesApi {
	readonly definitions: ActionQueueDefinition[];

	pause(queueId: number): void;

	resume(queueId: number): void;

	stats(queueId: number): ActionQueueStats;

	on(
		event: ActionQueueEvent,
		handler: (context: ActionQueueEventContext) => void
	): () => void;
}

/**
 * Toast notifications shown to the user.
 */
interface PluginAppToastApi {
	/**
	 * Show a transient toast notification.
	 *
	 * @example
	 * \`\`\`ts
	 * app.toast.create({
	 *   title: 'Connected',
	 *   description: 'WebSocket connection established.',
	 *   variant: 'success',
	 *   duration: 5000
	 * });
	 * \`\`\`
	 */
	create(props: ToastCreateProps): ToastItem;

	/**
	 * Dismiss a toast by id. Toasts auto-dismiss after their duration unless \`duration\` is \`0\`.
	 *
	 * @example
	 * \`\`\`ts
	 * const toast = app.toast.create({ title: 'Saving…', duration: 0 });
	 * await save();
	 * app.toast.dismiss(toast.id);
	 * \`\`\`
	 */
	dismiss(id: string): void;
}

/**
 * Confirmation dialogs that block until the user responds.
 */
interface PluginAppConfirmApi {
	/**
	 * Ask the user to confirm or cancel an action.
	 *
	 * @returns \`true\` when confirmed, \`false\` when cancelled.
	 *
	 * @example
	 * \`\`\`ts
	 * const confirmed = await app.confirm.ask({
	 *   title: 'Delete connection?',
	 *   description: 'This cannot be undone.'
	 * });
	 * if (confirmed) await deleteConnection();
	 * \`\`\`
	 */
	ask(options: ConfirmOptions): Promise<boolean>;
}

/**
 * Modal dialogs with custom Svelte content.
 */
interface PluginAppModalApi {
	/**
	 * Create a modal. Call \`open()\` on the returned instance to show it.
	 *
	 * Built-in npm plugins can pass Svelte components as \`content\`.
	 * Zip-installed plugins should use declarative page blocks instead of modals with Svelte content.
	 *
	 * @example
	 * \`\`\`ts
	 * const modal = app.modal.create({
	 *   id: 'edit-item',
	 *   title: 'Edit item',
	 *   content: EditItemModal,
	 *   props: { itemId: 'abc' },
	 *   size: 'md' // 'xs' | 'sm' | 'md' | 'lg' | 'full'
	 * });
	 * modal.open();
	 * \`\`\`
	 */
	create(props: ModalProps): Modal;

	/** Return an existing modal by id, if one was created earlier. */
	get(id: string): Modal | undefined;
}

/**
 * Access other plugins' public APIs.
 */
interface PluginAppPluginsApi {
	/**
	 * Get another plugin's public API by key. Throws if the plugin is missing or has no \`api\`.
	 *
	 * @example
	 * \`\`\`ts
	 * const twitch = app.plugins.get<TwitchPluginApi>('twitch');
	 * twitch.sendMessage('Hello chat!');
	 * \`\`\`
	 */
	get<TApi>(key: string): TApi;

	/**
	 * Get another plugin's public API, or \`undefined\` when unavailable.
	 *
	 * @example
	 * \`\`\`ts
	 * const obs = app.plugins.tryGet<ObsPluginApi>('obs');
	 * if (obs) await obs.connect();
	 * \`\`\`
	 */
	tryGet<TApi>(key: string): TApi | undefined;

	/**
	 * Read a plugin setting from the in-memory settings form (no save required).
	 *
	 * @example
	 * \`\`\`ts
	 * const enabled = app.plugins.getSettingValue('core', 'process-watcher') === true;
	 * \`\`\`
	 */
	getSettingValue(pluginKey: string, settingKey: string): SettingsFieldValue | undefined;

	/**
	 * Build lifecycle settings context for a plugin (store, getValue, app API).
	 */
	getSettingsContext(pluginKey: string): PluginSettingsContext | undefined;
}

/**
 * Sidebar menu entries registered at runtime.
 */
interface PluginAppMenuApi {
	/**
	 * Add a sidebar menu item owned by a plugin.
	 *
	 * @example
	 * \`\`\`ts
	 * app.menu.add({
	 *   path: '/plugins/my-plugin/dashboard',
	 *   title: 'Dashboard',
	 *   icon: 'ri:dashboard-line'
	 * });
	 * \`\`\`
	 */
	add(item: MenuItemLink): MenuItemLink;

	/**
	 * Remove a menu item by path.
	 *
	 * @example
	 * \`\`\`ts
	 * app.menu.remove('/plugins/my-plugin/dashboard');
	 * \`\`\`
	 */
	remove(path: string): void;
}

/**
 * Filesystem access through the app abstraction. Paths are relative to a {@link BaseDirectory} unless absolute.
 */
interface PluginAppFsApi {
	/**
	 * Open a native file or folder picker.
	 *
	 * @example
	 * \`\`\`ts
	 * const path = await app.fs.select({ type: 'file', filters: [{ name: 'JSON', extensions: ['json'] }] });
	 * \`\`\`
	 */
	select(options: FileSystemSelectOptions): Promise<string | null>;

	/**
	 * Open a native save dialog and return the chosen path, or \`null\` if cancelled.
	 *
	 * @example
	 * \`\`\`ts
	 * const path = await app.fs.save({
	 *   defaultPath: 'commands.json',
	 *   filters: [{ name: 'JSON', extensions: ['json'] }]
	 * });
	 * \`\`\`
	 */
	save(options?: FileSystemSaveOptions): Promise<string | null>;

	/** Join path segments using the platform separator. */
	join(...paths: string[]): Promise<string>;
	/**
	 * Create a file and return a handle for reading or writing.
	 *
	 * @example
	 * \`\`\`ts
	 * const handle = await app.fs.create('data.bin', { baseDir: BaseDirectory.AppData });
	 * await handle.write(new Uint8Array([1, 2, 3]));
	 * await handle.close();
	 * \`\`\`
	 */
	create(path: string | URL, options?: CreateOptions): Promise<FileHandle>;

	/**
	 * Open a file handle for reading, writing, or both.
	 *
	 * @example
	 * \`\`\`ts
	 * const handle = await app.fs.open('log.txt', {
	 *   baseDir: BaseDirectory.AppData,
	 *   read: true,
	 *   append: true
	 * });
	 * \`\`\`
	 */
	open(path: string | URL, options?: OpenOptions): Promise<FileHandle>;

	/**
	 * Copy a file from one path to another.
	 *
	 * @example
	 * \`\`\`ts
	 * await app.fs.copyFile('backup.json', 'backup-old.json', {
	 *   fromPathBaseDir: BaseDirectory.AppData,
	 *   toPathBaseDir: BaseDirectory.AppData
	 * });
	 * \`\`\`
	 */
	copyFile(fromPath: string | URL, toPath: string | URL, options?: CopyFileOptions): Promise<void>;

	/**
	 * Create a directory.
	 *
	 * @example
	 * \`\`\`ts
	 * await app.fs.mkdir('cache', { baseDir: BaseDirectory.AppData, recursive: true });
	 * \`\`\`
	 */
	mkdir(path: string | URL, options?: MkdirOptions): Promise<void>;

	/**
	 * Read directory entries.
	 *
	 * @example
	 * \`\`\`ts
	 * const entries = await app.fs.readDir('.', { baseDir: BaseDirectory.AppData });
	 * \`\`\`
	 */
	readDir(path: string | URL, options?: ReadDirOptions): Promise<DirEntry[]>;

	/** Read a file as bytes. */
	readFile(path: string | URL, options?: ReadFileOptions): Promise<Uint8Array>;

	/**
	 * Read a file as UTF-8 text.
	 *
	 * @example
	 * \`\`\`ts
	 * const json = await app.fs.readTextFile('settings.json', { baseDir: BaseDirectory.AppData });
	 * \`\`\`
	 */
	readTextFile(path: string | URL, options?: ReadFileOptions): Promise<string>;

	/** Read a file line-by-line. */
	readTextFileLines(
		path: string | URL,
		options?: ReadFileOptions
	): Promise<AsyncIterableIterator<string>>;

	/**
	 * Delete a file or directory.
	 *
	 * @example
	 * \`\`\`ts
	 * await app.fs.remove('cache/temp.json', { baseDir: BaseDirectory.AppData });
	 * \`\`\`
	 */
	remove(path: string | URL, options?: RemoveOptions): Promise<void>;

	/** Rename or move a file. */
	rename(oldPath: string | URL, newPath: string | URL, options?: RenameOptions): Promise<void>;

	/** Get file metadata. */
	stat(path: string | URL, options?: StatOptions): Promise<FileInfo>;

	/** Get symlink metadata without following links. */
	lstat(path: string | URL, options?: StatOptions): Promise<FileInfo>;

	/** Truncate a file to a length. */
	truncate(path: string | URL, len?: number, options?: TruncateOptions): Promise<void>;

	/** Write bytes to a file. */
	writeFile(
		path: string | URL,
		data: Uint8Array | ReadableStream<Uint8Array>,
		options?: WriteFileOptions
	): Promise<void>;

	/**
	 * Write UTF-8 text to a file.
	 *
	 * @example
	 * \`\`\`ts
	 * await app.fs.writeTextFile('settings.json', JSON.stringify(data), {
	 *   baseDir: BaseDirectory.AppData,
	 *   create: true
	 * });
	 * \`\`\`
	 */
	writeTextFile(path: string | URL, data: string, options?: WriteFileOptions): Promise<void>;

	/**
	 * Check whether a path exists.
	 *
	 * @example
	 * \`\`\`ts
	 * if (await app.fs.exists('settings.json', { baseDir: BaseDirectory.AppData })) { ... }
	 * \`\`\`
	 */
	exists(path: string | URL, options?: ExistsOptions): Promise<boolean>;

	/** Watch paths with debounced callbacks. */
	watch(
		paths: string | string[] | URL | URL[],
		callback: (event: WatchEvent) => void,
		options?: DebouncedWatchOptions
	): Promise<UnwatchFn>;

	/** Watch paths with immediate callbacks. */
	watchImmediate(
		paths: string | string[] | URL | URL[],
		callback: (event: WatchEvent) => void,
		options?: WatchOptions
	): Promise<UnwatchFn>;

	/** Return file size in bytes. */
	size(path: string | URL): Promise<number>;
}

/**
 * Application lifecycle events (start/exit).
 */
interface PluginAppLifecycleApi {
	/** Whether the app has finished booting and emitted the started event. */
	readonly started: boolean;

	/** Subscribe to app-started events. Returns an unsubscribe function. */
	onStarted(handler: (context: AppLifecycleContext) => void): () => void;

	/**
	 * Subscribe to app-exit events. Returns an unsubscribe function.
	 *
	 * The handler may return a promise; the window stays open until all exit
	 * handlers settle, allowing async cleanup (flush stores, disconnect, etc.).
	 */
	onExit(handler: (context: AppLifecycleContext) => void | Promise<void>): () => void;

	/** Build a lifecycle context for the given event. */
	getContext(event: AppLifecycleEvent): AppLifecycleContext;
}

/**
 * OS process lifecycle events (start/stop).
 */
interface PluginAppProcessApi {
	/** Whether the Rust process watcher is currently polling. */
	readonly running: boolean;

	/**
	 * Start or stop the OS process watcher.
	 *
	 * @example
	 * \`\`\`ts
	 * await app.process.sync(getValue('process-watcher') === true);
	 * \`\`\`
	 */
	sync(enabled: boolean): Promise<void>;

	/** Subscribe to process-started events. Returns an unsubscribe function. */
	onStarted(handler: (context: ProcessEventContext) => void): () => void;

	/** Subscribe to process-stopped events. Returns an unsubscribe function. */
	onStopped(handler: (context: ProcessEventContext) => void): () => void;

	/**
	 * Run an external program, script, or shell command.
	 *
	 * @example
	 * \`\`\`ts
	 * const result = await app.process.run({
	 *   command: 'C:\\\\Tools\\\\node.exe',
	 *   workingDirectory: 'C:\\\\Scripts',
	 *   arguments: 'hello.js {user}',
	 *   waitSeconds: 5
	 * });
	 * \`\`\`
	 */
	run(options: RunProgramOptions): Promise<RunProgramResult>;
}

/**
 * Local media file helpers (duration probing, etc.).
 */
interface PluginAppMediaApi {
	/** Returns the duration of a local video/audio file in milliseconds, or null when unknown. */
	getFileDurationMs(filePath: string): Promise<number | null>;
}

/**
 * Lightweight network reachability checks that avoid noisy browser WebSocket errors.
 */
interface PluginAppNetworkApi {
	/** Returns whether a TCP port accepts connections on the given host. */
	isTcpPortReachable(host: string, port: number, timeoutMs?: number): Promise<boolean>;
}

/**
 * Audio playback helpers.
 */
interface PluginAppAudioPlayOptions {
	/** Optional session id used to stop this playback via {@link PluginAppAudioApi.stop}. */
	sessionId?: string;
}

/**
 * Audio playback helpers.
 */
interface PluginAppAudioApi {
	/**
	 * Play audio from a blob. Volume is clamped between \`0\` and \`2\` (\`1\` = 100%).
	 *
	 * @example
	 * \`\`\`ts
	 * const blob = await fetch('/sounds/alert.mp3').then((r) => r.blob());
	 * await app.audio.play(blob, 0.8);
	 * \`\`\`
	 */
	play(blob: Blob, volume?: number, options?: PluginAppAudioPlayOptions): Promise<void>;
	/**
	 * Play audio from a file path. The file is read and decoded in the app layer.
	 * Prefer this over \`play\` for local files to avoid loading large files into memory.
	 */
	playFile(path: string, volume?: number, options?: PluginAppAudioPlayOptions): Promise<void>;
	/** Stop the active playback for the given session id. No-op when nothing is playing. */
	stop(sessionId: string): Promise<void>;
}

/**
 * Authenticated cloud user media (\`user_files\` in PocketBase).
 */
interface PluginAppUserFileRecord {
	id: string;
	url: string;
	size: number;
	mimeType: string;
	originalName: string;
	createdAt: string | null;
}

interface PluginAppUserFilesQuota {
	usedBytes: number;
	maxStorageBytes: number;
	maxFileBytes: number;
	planKey: string;
	planName: string;
}

interface PluginAppUserFilesListOptions {
	mimePrefix?: string;
	extensions?: string[];
}

interface PluginAppUserFilesUploadOptions {
	originalName: string;
}

interface PluginAppUserFilesApi {
	/** True when the value looks like an \`http(s)\` cloud file URL. */
	isCloudUrl(value: string | null | undefined): boolean;
	/** List the signed-in user's cloud files (optional mime/extension filters). */
	list(options?: PluginAppUserFilesListOptions): Promise<PluginAppUserFileRecord[]>;
	/** Upload a file/blob; requires auth + active subscription within plan limits. */
	upload(
		file: File | Blob,
		options: PluginAppUserFilesUploadOptions
	): Promise<PluginAppUserFileRecord>;
	/** Delete one of the signed-in user's cloud files. */
	remove(id: string): Promise<void>;
	/** Current plan quota usage, or \`null\` when signed out / no active plan. */
	getQuota(): Promise<PluginAppUserFilesQuota | null>;
	/** Download a private cloud file URL with the signed-in auth token. */
	fetchBlob(url: string): Promise<Blob>;
	/** Open the app cloud file picker modal; resolves \`null\` when cancelled. */
	pick(options?: PluginAppUserFilesListOptions): Promise<PluginAppUserFileRecord | null>;
}

/**
 * App-owned bridge to the local (Piper) TTS runtime. Keeps Tauri command
 * invocation in the app layer so plugins stay platform-agnostic.
 */
interface PluginAppLocalTtsApi {
	/** List all known local voices (installed and downloadable). */
	listVoices(): Promise<LocalTtsVoiceInfo[]>;

	/** Whether the local TTS runtime is installed. */
	getRuntimeInfo(): Promise<LocalTtsRuntimeInfo>;

	/** Download and install the local TTS runtime. */
	downloadRuntime(): Promise<void>;

	/** Download and install a specific voice. */
	downloadVoice(voiceId: string): Promise<void>;

	/** Delete a downloaded voice. */
	deleteVoice(voiceId: string): Promise<void>;

	/** Synthesize speech as WAV bytes for the given voice and text. */
	synthesize(voiceId: string, text: string): Promise<Uint8Array>;
}

/**
 * Translations for plugin UI and runtime messages.
 */
interface PluginAppI18nApi {
	/** Reactive translation function for Svelte components. */
	t: (key: TranslationKey, params?: Record<string, string | number | null | undefined>) => string;

	/** Non-reactive translation helper for TypeScript modules. */
	translate(
		key: TranslationKey,
		params?: Record<string, string | number | null | undefined>
	): string;
}

/**
 * Plugin database migration registration.
 */
interface PluginAppDbApi {
	/**
	 * Register SQLite migrations to run on app startup for this plugin key.
	 *
	 * @example
	 * \`\`\`ts
	 * app.db.registerMigrations('my-plugin', [
	 *   async (sqlite) => {
	 *     await sqlite.execute('CREATE TABLE IF NOT EXISTS my_plugin_items (id INTEGER PRIMARY KEY)');
	 *   }
	 * ]);
	 * \`\`\`
	 */
	registerMigrations(pluginKey: string, migrations: PluginMigration[]): void;

	/**
	 * Return the shared Drizzle database client.
	 * Only use this when the plugin registers its own SQLite tables via {@link registerMigrations}.
	 */
	getClient(): PluginDbClient;
}

/**
 * User-configured action runtime.
 */
interface PluginAppActionsApi {
	/**
	 * Deactivate and reactivate all enabled actions. Useful after plugin settings change trigger/handler availability.
	 *
	 * @example
	 * \`\`\`ts
	 * onSave: async ({ app }) => {
	 *   app.actions.reactivateAll();
	 * }
	 * \`\`\`
	 */
	reactivateAll(): void;

	/** Whether any enabled action uses a Process Started or Process Stopped trigger. */
	hasEnabledProcessTrigger(): boolean;

	/**
	 * Run a stored action by database id with trigger context.
	 *
	 * @returns \`true\` when the action ran successfully.
	 *
	 * @example
	 * \`\`\`ts
	 * app.actions.runById(42, { trigger: 'manual', data: {} });
	 * \`\`\`
	 */
	runById(id: number, context: HandlerTriggerContext): boolean;

	/** Find a registered action handler definition by id. */
	findHandler(id: string): HandlerDefinition | undefined;

	/** Return all registered action handler definitions. */
	getHandlers(): HandlerDefinition[];

	/**
	 * Create a user-configured action record.
	 *
	 * @example
	 * \`\`\`ts
	 * await app.actions.create({
	 *   name: 'Points on follow',
	 *   group: pluginKey,
	 *   enabled: false,
	 *   triggers: [...],
	 *   handlers: [...]
	 * });
	 * \`\`\`
	 */
	create(input: NewActionRecord, options?: { ownerPluginKey?: string }): Promise<ActionRecord>;

	/**
	 * Update an existing action by database id.
	 */
	update(
		id: number,
		input: Omit<NewActionRecord, 'id'>,
		options?: { ownerPluginKey?: string }
	): Promise<ActionRecord>;

	/** Delete an action by database id. */
	delete(id: number): Promise<void>;

	/** Delete all actions owned by a plugin. */
	deleteByOwner(ownerPluginKey: string): Promise<number>;

	/** Return all configured actions as records. */
	getSnapshot(): ActionRecord[];
}

/**
 * Inbound WebSocket API server — plugins register methods and emit events for remote clients.
 */
interface PluginAppApiServerApi {
	/**
	 * Register a request method. When called from a plugin scope, the name is prefixed with
	 * \`plugin:<pluginKey>:\`.
	 *
	 * @example
	 * \`\`\`ts
	 * app.api.registerMethod('getLeaderboard', async () => rankings.getLeaderboard());
	 * // → plugin:rankings:getLeaderboard
	 * \`\`\`
	 */
	registerMethod(
		name: string,
		handler: (params: unknown) => unknown | Promise<unknown>
	): void;

	/**
	 * Emit an event to subscribed WebSocket clients. Prefixed with \`plugin:<pluginKey>:\` in plugin scope.
	 */
	emit(event: string, payload?: unknown): Promise<void>;

	/** Remove all methods registered by the current plugin. */
	unregisterMethods(): void;
}

/**
 * Chat commands plugin integration. Requires the Commands plugin to be enabled.
 */
interface PluginAppCommandsApi {
	/**
	 * Register a runtime factory with the Commands plugin.
	 *
	 * @example
	 * \`\`\`ts
	 * app.commands.registerRuntime((app) => () => {
	 *   // setup listeners; return teardown function
	 *   return () => { /* cleanup *\\/ };
	 * });
	 * \`\`\`
	 */
	registerRuntime(factory: CommandRuntimeFactory): void;

	/**
	 * Return a snapshot of all configured chat commands.
	 *
	 * @example
	 * \`\`\`ts
	 * const commands = app.commands.getSnapshot();
	 * \`\`\`
	 */
	getSnapshot(): CommandRecord[];

	/**
	 * Run a chat command by id.
	 *
	 * @returns \`true\` when the command ran successfully.
	 */
	runById(id: string, context: HandlerTriggerContext): boolean;

	/**
	 * Find a command record by its trigger string (e.g. \`!hello\`).
	 *
	 * @example
	 * \`\`\`ts
	 * const command = app.commands.findByTrigger('!hello');
	 * \`\`\`
	 */
	findByTrigger(trigger: string): CommandRecord | undefined;

	/**
	 * Create a chat command record.
	 *
	 * @example
	 * \`\`\`ts
	 * await app.commands.create({
	 *   name: 'Ping',
	 *   commandNames: ['ping'],
	 *   handlers: [{ id: crypto.randomUUID(), handlerTypeId: 'core:core:chat:send-message', fields: [] }]
	 * });
	 * \`\`\`
	 */
	create(
		input: NewCommandRecord,
		options?: { ownerPluginKey?: string }
	): Promise<CommandRecord>;

	/**
	 * Update an existing chat command by id.
	 */
	update(
		id: string,
		input: Omit<NewCommandRecord, 'id'>,
		options?: { ownerPluginKey?: string }
	): Promise<CommandRecord>;

	/** Delete a chat command by id. Returns \`false\` when the command does not exist. */
	delete(id: string): Promise<boolean>;

	/** Delete all commands owned by a plugin. Returns the number of deleted commands. */
	deleteByOwner(ownerPluginKey: string): Promise<number>;
}

/**
 * Stream Kit account authentication (PocketBase).
 */
interface PluginAppAuthApi {
	/** Public profile of the signed-in user, or \`null\` when logged out. */
	readonly user: AuthPublicUser | null;

	/** Whether a Stream Kit account session is active. */
	readonly isAuthenticated: boolean;

	/**
	 * Sign in with email and password.
	 *
	 * @example
	 * \`\`\`ts
	 * await app.auth.login({ email: 'you@example.com', password: 'secret' });
	 * \`\`\`
	 */
	login(input: AuthLoginInput): Promise<void>;

	/**
	 * Create a Stream Kit account and sign in.
	 *
	 * @example
	 * \`\`\`ts
	 * await app.auth.register({
	 *   email: 'you@example.com',
	 *   password: 'secret',
	 *   passwordConfirm: 'secret',
	 *   name: 'You'
	 * });
	 * \`\`\`
	 */
	register(input: AuthRegisterInput): Promise<void>;

	/** Clear the current session. */
	logout(): Promise<void>;

	/**
	 * Subscribe to auth changes. Invoked immediately with the current user.
	 * Returns an unsubscribe function.
	 */
	onChange(handler: (user: AuthPublicUser | null) => void): () => void;
}

/**
 * OAuth redirect flow helpers via the Tauri OAuth plugin.
 */
interface PluginAppOAuthApi {
	/**
	 * Start a local OAuth redirect server and return the bound port.
	 *
	 * @example
	 * \`\`\`ts
	 * const port = await app.oauth.start({ ports: [5173, 5174] });
	 * \`\`\`
	 */
	start(options?: OAuthStartOptions): Promise<number>;

	/**
	 * Listen for OAuth redirect URLs. Returns an unlisten function.
	 *
	 * @example
	 * \`\`\`ts
	 * const unlisten = await app.oauth.onUrl((url) => {
	 *   console.log('OAuth callback:', url);
	 * });
	 * \`\`\`
	 */
	onUrl(callback: (url: string) => void): Promise<UnlistenFn>;

	/**
	 * Listen for invalid OAuth redirect URLs. Returns an unlisten function.
	 */
	onInvalidUrl(callback: (url: string) => void): Promise<UnlistenFn>;
}

/**
 * Toolbar below the app header (meta badges, primary actions, bulk selection).
 */
interface PluginAppToolbarApi {
	set(config: ToolbarConfig): void;

	reset(): void;
}

/**
 * Open URLs in the system default browser.
 */
interface PluginAppOpenerApi {
	/**
	 * Open a URL externally.
	 *
	 * @example
	 * \`\`\`ts
	 * await app.opener.openUrl('https://streamkit.dev/docs');
	 * \`\`\`
	 */
	openUrl(url: string): Promise<void>;
}

/**
 * Broadcast events to OBS browser-source overlays.
 */
interface PluginAppOverlayApi {
	/** Current overlay projects (id, name, expected events). */
	readonly items: Array<{
		id: string;
		name: string;
		expectedEvents: string[];
	}>;

	/** Push an event payload to a connected overlay. */
	broadcast(overlayId: string, event: string, payload?: unknown): Promise<void>;
}

/**
 * APIs available to plugin authors via the \`app\` parameter and lifecycle {@link PluginSettingsContext}.
 */
interface PluginAppApi {
	/** Show transient notifications to the user. */
	toast: PluginAppToastApi;

	/** Ask the user to confirm destructive actions. */
	confirm: PluginAppConfirmApi;

	/** Create modal dialogs with custom content. */
	modal: PluginAppModalApi;

	/** Access other plugins' public APIs. */
	plugins: PluginAppPluginsApi;

	/** Register sidebar menu items at runtime. */
	menu: PluginAppMenuApi;

	/** Configure the toolbar below the app header. */
	toolbar: PluginAppToolbarApi;

	/** Read and write files through the app filesystem abstraction. */
	fs: PluginAppFsApi;

	/** Play audio blobs. */
	audio: PluginAppAudioApi;

	/** Authenticated cloud user media library (\`user_files\`). */
	userFiles: PluginAppUserFilesApi;

	/** Probe local media files (for example video duration). */
	media: PluginAppMediaApi;

	/** Lightweight network reachability checks. */
	network: PluginAppNetworkApi;

	/** Bridge to the local (Piper) TTS runtime. */
	localTts: PluginAppLocalTtsApi;

	/** Application start and exit events. */
	lifecycle: PluginAppLifecycleApi;

	/** Watch OS process start/stop events. */
	process: PluginAppProcessApi;

	/** Register global keyboard shortcut listeners. */
	hotkeys: PluginAppHotkeysApi;

	/** Control and observe action queues. */
	actionQueues: PluginAppActionQueuesApi;

	/** Register plugin database migrations. */
	db: PluginAppDbApi;

	/** Translate user-facing strings. */
	i18n: PluginAppI18nApi;

	/** Run and refresh user-configured actions. */
	actions: PluginAppActionsApi;

	/** Integrate with the Commands plugin. */
	commands: PluginAppCommandsApi;

	/** Stream Kit account authentication and public profile. */
	auth: PluginAppAuthApi;

	/** OAuth redirect flow helpers. */
	oauth: PluginAppOAuthApi;

	/** Open URLs in the default browser. */
	opener: PluginAppOpenerApi;

	/** Send events to browser-source overlays. */
	overlay: PluginAppOverlayApi;

	/** Extend the inbound WebSocket API server with plugin methods and events. */
	api: PluginAppApiServerApi;

	/**
	 * Serialize work that touches the same shared resource across concurrent action runs.
	 *
	 * @example
	 * \`\`\`ts
	 * await app.withResourceLock('obs:media:alerts', async () => {
	 *   await updateObsMediaSource();
	 * });
	 * \`\`\`
	 */
	withResourceLock<T>(key: string, fn: () => Promise<T>): Promise<T>;
}
`;
export const triggerDataDts = `/** Stubs for types referenced by plugin trigger contexts. */
type TwitchChatMessage = {
	channelId: string | null;
	id: string;
	message: string;
	date: string;
	isCheer: boolean;
	isRedemption: boolean;
	isHypeChat: boolean;
	isFirst: boolean;
	isReturningChatter: boolean;
	isHighlight: boolean;
	isReply: boolean;
	bits: number;
	rewardId: string | null;
	hypeChatLocalizedAmount: number | null;
	hypeChatLevel: number | null;
	parentMessageUserName: string | null;
	parentMessageText: string | null;
	parentMessageUserDisplayName: string | null;
	badges: { id: string; version: string; url: string }[];
	badgeInfo: Record<string, string>;
	emotes: { id: string; positions: string[]; url: string }[];
	userInfo: {
		userId: string | undefined;
		userName: string;
		displayName: string;
		color: string | undefined;
		userType: string | undefined;
		isMod: boolean;
		isBroadcaster: boolean;
		isVip: boolean;
		isSubscriber: boolean;
		isArtist: boolean;
		isFounder: boolean;
	};
};

type ProcessEventContext = {
	executable?: string;
	fullPath?: string;
	name?: string;
	parentProcessId?: number;
	path?: string;
	processId?: number;
};

type AppLifecycleEvent = 'started' | 'exit';

type AppLifecycleContext = {
	event: AppLifecycleEvent;
};


type TwitchChatBadge = {
	id: string;
	version: string;
	url: string;
};
type TwitchChatEmote = {
	id: string;
	positions: string[];
	url: string;
};
type TwitchChatUserInfo = {
	userId: string | undefined;
	userName: string;
	displayName: string;
	color: string | undefined;
	userType: string | undefined;
	isMod: boolean;
	isBroadcaster: boolean;
	isVip: boolean;
	isSubscriber: boolean;
	isArtist: boolean;
	isFounder: boolean;
};
type TwitchBaseContext = {
	broadcasterId: string;
	channel: string;
};
type ChatMessageContext = TwitchBaseContext & {
	user: string;
	userId: string;
	message: string;
	role: string;
	msg: TwitchChatMessage;
};
type WhisperContext = TwitchBaseContext & {
	user: string;
	message: string;
};
type CheerContext = ChatMessageContext & {
	bits: number;
};
type RedemptionContext = ChatMessageContext & {
	rewardId: string;
};
type CommandContext = ChatMessageContext & {
	command: string;
	args: Record<string, string>;
};
type HypeChatContext = ChatMessageContext & {
	amount: number;
};
type SubContext = TwitchBaseContext & {
	user: string;
	tier: string;
	months?: number;
};
type GiftSubContext = TwitchBaseContext & {
	user: string;
	tier: string;
	giftCount: number;
};
type CommunitySubContext = TwitchBaseContext & {
	user: string;
	giftCount: number;
};
type RaidContext = TwitchBaseContext & {
	user: string;
	viewers: number;
};
type ModerationContext = TwitchBaseContext & {
	user: string;
	duration?: number;
};
type UserJoinPartContext = TwitchBaseContext & {
	user: string;
};
type StreamContext = TwitchBaseContext & {
	streamId?: string;
};
type FollowContext = TwitchBaseContext & {
	user: string;
	userId: string;
};
type ChannelUpdateContext = TwitchBaseContext & {
	title: string;
	game: string;
};
type PointsRedemptionContext = TwitchBaseContext & {
	user: string;
	userId: string;
	rewardId: string;
	rewardTitle: string;
	redemptionId: string;
	input: string;
};
type HypeTrainContext = TwitchBaseContext & {
	level: number;
	total: number;
	progress: number;
	goal: number;
};
type PollContext = TwitchBaseContext & {
	pollId: string;
	title: string;
};
type PredictionContext = TwitchBaseContext & {
	predictionId: string;
	title: string;
};
type EventSubModerationContext = TwitchBaseContext & {
	user: string;
	userId: string;
	reason?: string;
};
type GoalContext = TwitchBaseContext & {
	goalId: string;
	type: string;
	description: string;
	currentAmount: number;
	targetAmount: number;
	isAchieved?: boolean;
};
type CharityContext = TwitchBaseContext & {
	campaignId: string;
	charityName: string;
	currency: string;
	currentAmount?: number;
	targetAmount?: number;
	user?: string;
	userId?: string;
	amount?: number;
};
type AdBreakContext = TwitchBaseContext & {
	durationSeconds: number;
	isAutomatic: boolean;
	requester: string;
	requesterId: string;
};
type ShoutoutReceivedContext = TwitchBaseContext & {
	user: string;
	userId: string;
	viewers: number;
};
type TwitchContext = | ChatMessageContext
	| WhisperContext
	| CheerContext
	| RedemptionContext
	| CommandContext
	| HypeChatContext
	| SubContext
	| GiftSubContext
	| CommunitySubContext
	| RaidContext
	| ModerationContext
	| UserJoinPartContext
	| StreamContext
	| FollowContext
	| ChannelUpdateContext
	| PointsRedemptionContext
	| HypeTrainContext
	| PollContext
	| PredictionContext
	| EventSubModerationContext
	| GoalContext
	| CharityContext
	| AdBreakContext
	| ShoutoutReceivedContext;
type YouTubeAuthorDetails = {
	channelId: string;
	channelUrl: string;
	displayName: string;
	profileImageUrl: string;
	isVerified: boolean;
	isChatOwner: boolean;
	isChatSponsor: boolean;
	isChatModerator: boolean;
};
type YouTubeLiveChatMessageType = | 'textMessageEvent'
	| 'superChatEvent'
	| 'superStickerEvent'
	| 'newSponsorEvent'
	| 'memberMilestoneChatEvent'
	| 'membershipGiftingEvent'
	| 'giftMembershipReceivedEvent'
	| 'giftEvent'
	| 'userBannedEvent'
	| 'messageDeletedEvent'
	| 'pollEvent'
	| 'sponsorOnlyModeStartedEvent'
	| 'sponsorOnlyModeEndedEvent'
	| 'chatEndedEvent'
	| 'tombstone';
type YouTubeLiveChatMessage = {
	kind: 'youtube#liveChatMessage';
	id: string;
	snippet: {
		type: YouTubeLiveChatMessageType;
		liveChatId: string;
		authorChannelId?: string;
		publishedAt: string;
		hasDisplayContent?: boolean;
		displayMessage?: string;
		textMessageDetails?: {
			messageText: string;
		};
		superChatDetails?: {
			amountMicros: string;
			currency: string;
			amountDisplayString: string;
			userComment?: string;
			tier: number;
		};
		superStickerDetails?: {
			amountMicros: string;
			currency: string;
			amountDisplayString: string;
			tier: number;
			superStickerMetadata?: {
				stickerId: string;
				altText: string;
				language: string;
			};
		};
		newSponsorDetails?: {
			memberLevelName?: string;
			isUpgrade?: boolean;
		};
		memberMilestoneChatDetails?: {
			userComment?: string;
			memberMonth: number;
			memberLevelName?: string;
		};
		membershipGiftingDetails?: {
			giftMembershipsCount: number;
			giftMembershipsLevelName?: string;
		};
		giftMembershipReceivedDetails?: {
			memberLevelName?: string;
			gifterChannelId: string;
			associatedMembershipGiftingMessageId: string;
		};
		giftEventDetails?: {
			giftMetadata?: {
				jewelsAmount: number;
				giftName: string;
				giftUrl?: string;
				altText?: string;
			};
		};
		userBannedDetails?: {
			bannedUserDetails: {
				channelId: string;
				displayName: string;
			};
			banType: 'permanent' | 'temporary';
			banDurationSeconds?: string;
		};
		messageDeletedDetails?: {
			deletedMessageId: string;
		};
		pollDetails?: {
			metadata?: {
				questionText: string;
				status: 'unknown' | 'active' | 'closed';
				options?: Array<{
					optionText: string;
					tally?: string;
				}>;
			};
		};
	};
	authorDetails?: YouTubeAuthorDetails;
};
type YouTubeLiveChatMessageListResponse = {
	kind: 'youtube#liveChatMessageListResponse';
	nextPageToken?: string;
	pollingIntervalMillis?: number;
	offlineAt?: string;
	items?: YouTubeLiveChatMessage[];
};
type YouTubeLiveBroadcast = {
	kind: 'youtube#liveBroadcast';
	id: string;
	snippet: {
		channelId: string;
		title: string;
		liveChatId?: string;
		actualStartTime?: string;
		actualEndTime?: string;
	};
	status: {
		lifeCycleStatus: 'created' | 'ready' | 'testing' | 'live' | 'complete' | 'revoked';
		privacyStatus: string;
	};
};
type YouTubeLiveBroadcastListResponse = {
	kind: 'youtube#liveBroadcastListResponse';
	items?: YouTubeLiveBroadcast[];
};
type YouTubeChannel = {
	kind: 'youtube#channel';
	id: string;
	snippet: {
		title: string;
		customUrl?: string;
	};
};
type YouTubeChannelListResponse = {
	kind: 'youtube#channelListResponse';
	items?: YouTubeChannel[];
};
type YouTubeTokenResponse = {
	access_token: string;
	expires_in: number;
	refresh_token?: string;
	token_type: string;
	scope: string;
};
type YouTubeChannelInfo = {
	channelId: string;
	channelTitle: string;
	customUrl?: string;
};
type YouTubeLiveStreamInfo = {
	broadcastId: string;
	liveChatId: string;
	title: string;
	actualStartTime?: string;
};
type YouTubeBaseContext = {
	channelId: string;
	channel: string;
	liveChatId: string;
	broadcastId: string;
};
type SuperChatContext = YouTubeBaseContext & {
	user: string;
	userId: string;
	message: string;
	role: string;
	amount: string;
	amountMicros: number;
	currency: string;
	tier: number;
	raw: YouTubeLiveChatMessage;
};
type SuperStickerContext = SuperChatContext & {
	stickerId: string;
};
type NewMemberContext = YouTubeBaseContext & {
	user: string;
	userId: string;
	memberLevelName: string;
	isUpgrade: boolean;
	raw: YouTubeLiveChatMessage;
};
type MemberMilestoneContext = YouTubeBaseContext & {
	user: string;
	userId: string;
	message: string;
	memberMonth: number;
	memberLevelName: string;
	raw: YouTubeLiveChatMessage;
};
type MembershipGiftContext = YouTubeBaseContext & {
	user: string;
	userId: string;
	giftCount: number;
	memberLevelName: string;
	raw: YouTubeLiveChatMessage;
};
type GiftMembershipReceivedContext = YouTubeBaseContext & {
	user: string;
	userId: string;
	memberLevelName: string;
	gifterChannelId: string;
	raw: YouTubeLiveChatMessage;
};
type GiftContext = YouTubeBaseContext & {
	user: string;
	userId: string;
	giftName: string;
	jewelsAmount: number;
	raw: YouTubeLiveChatMessage;
};
type MessageDeletedContext = YouTubeBaseContext & {
	user: string;
	userId: string;
	deletedMessageId: string;
	raw: YouTubeLiveChatMessage;
};
type SponsorsOnlyContext = YouTubeBaseContext & {
	raw: YouTubeLiveChatMessage;
};
type ChatEndedContext = YouTubeBaseContext & {
	raw: YouTubeLiveChatMessage | undefined;
};
type YouTubeContext = | ChatMessageContext
	| CommandContext
	| SuperChatContext
	| SuperStickerContext
	| NewMemberContext
	| MemberMilestoneContext
	| MembershipGiftContext
	| GiftMembershipReceivedContext
	| GiftContext
	| ModerationContext
	| MessageDeletedContext
	| PollContext
	| SponsorsOnlyContext
	| ChatEndedContext
	| StreamContext;
type SceneChangedContext = {
	sceneName: string;
	sceneUuid: string;
};
type OutputStateContext = {
	outputActive: boolean;
	outputState: string;
	outputPath?: string;
};
type RecordFileChangedContext = {
	newOutputPath: string;
};
type TransitionContext = {
	transitionName: string;
	transitionUuid?: string;
};
type InputStateContext = {
	inputName: string;
	inputUuid?: string;
	inputMuted?: boolean;
	inputEnabled?: boolean;
};
type MediaContext = {
	inputName: string;
	inputUuid?: string;
};
type MediaActionContext = {
	inputName: string;
	inputUuid?: string;
	mediaAction: string;
};
type FilterContext = {
	sourceName: string;
	filterName: string;
	filterEnabled: boolean;
};
type ReplayBufferContext = OutputStateContext;
type VirtualCamContext = OutputStateContext;
type StudioModeContext = {
	studioModeEnabled: boolean;
};
type ObsContext = | SceneChangedContext
	| OutputStateContext
	| RecordFileChangedContext
	| TransitionContext
	| InputStateContext
	| MediaContext
	| MediaActionContext
	| FilterContext
	| ReplayBufferContext
	| VirtualCamContext
	| StudioModeContext;
type ScheduleRepeat = 'once' | 'daily' | 'weekly';
type ScheduleEventContext = {
	kind: 'cron' | 'scheduled';
	firedAt: string;
	scheduledAt: string;
	cronExpression?: string;
	date?: string;
	time?: string;
	repeat?: ScheduleRepeat;
	weekday?: string;
};
type WsMessageContext = {
	connectionId: string;
	connectionName: string;
	url: string;
	message: string;
	isJson: boolean;
	data?: unknown;
	/** Logical connections that share the same pooled socket. */
	affectedConnectionIds?: string[];
};
type WsConnectionStateContext = {
	connectionId: string;
	connectionName: string;
	url: string;
	/** Logical connections that share the same pooled socket. */
	affectedConnectionIds?: string[];
};
type OverlayMessageContext = {
	overlayId: string;
	event: string;
	payload: unknown;
	/** JSON string of \`payload\`. */
	message: string;
	timestamp: number;
};

type TriggerDataUnion = ProcessEventContext | AppLifecycleContext | TwitchBaseContext | ChatMessageContext | WhisperContext | CheerContext | RedemptionContext | CommandContext | HypeChatContext | SubContext | GiftSubContext | CommunitySubContext | RaidContext | ModerationContext | UserJoinPartContext | StreamContext | FollowContext | ChannelUpdateContext | PointsRedemptionContext | HypeTrainContext | PollContext | PredictionContext | EventSubModerationContext | GoalContext | CharityContext | AdBreakContext | ShoutoutReceivedContext | TwitchContext | YouTubeBaseContext | SuperChatContext | SuperStickerContext | NewMemberContext | MemberMilestoneContext | MembershipGiftContext | GiftMembershipReceivedContext | GiftContext | MessageDeletedContext | SponsorsOnlyContext | ChatEndedContext | YouTubeContext | SceneChangedContext | OutputStateContext | RecordFileChangedContext | TransitionContext | InputStateContext | MediaContext | MediaActionContext | FilterContext | ReplayBufferContext | VirtualCamContext | StudioModeContext | ObsContext | ScheduleEventContext | WsMessageContext | WsConnectionStateContext | OverlayMessageContext;
`;
export const triggerMap = {
	"core:core:input:hotkey": "HotkeyEventContext",
	"core:core:queue:queue-paused": "ActionQueueEventContext",
	"core:core:queue:queue-resumed": "ActionQueueEventContext",
	"core:core:queue:queue-became-idle": "ActionQueueEventContext",
	"core:core:queue:queue-job-enqueued": "ActionQueueEventContext",
	"core:core:queue:queue-job-started": "ActionQueueEventContext",
	"core:core:queue:queue-job-completed": "ActionQueueEventContext",
	"core:processes:process-started": "ProcessEventContext",
	"core:processes:process-stopped": "ProcessEventContext",
	"core:app:app-started": "AppLifecycleContext",
	"core:app:app-exit": "AppLifecycleContext",
	"discord:discord:message:message-received": "MessageReceivedContext",
	"discord:discord:role:role-added": "RoleChangedContext",
	"discord:discord:role:role-removed": "RoleChangedContext",
	"discord:discord:voice:voice-join": "VoiceStateChangedContext",
	"discord:discord:voice:voice-leave": "VoiceStateChangedContext",
	"discord:discord:voice:voice-move": "VoiceStateChangedContext",
	"obs:obs:scene:preview-scene-changed": "SceneChangedContext",
	"obs:obs:stream:createstreamstartingtrigger": "OutputStateContext",
	"obs:obs:stream:stream-started": "OutputStateContext",
	"obs:obs:stream:createstreamstoppingtrigger": "OutputStateContext",
	"obs:obs:stream:stream-stopped": "OutputStateContext",
	"obs:obs:stream:createstreamreconnectingtrigger": "OutputStateContext",
	"obs:obs:recording:recording-started": "OutputStateContext",
	"obs:obs:recording:createrecordingpausedtrigger": "OutputStateContext",
	"obs:obs:recording:createrecordingresumedtrigger": "OutputStateContext",
	"obs:obs:recording:recording-stopped": "OutputStateContext",
	"obs:obs:recording:record-file-changed": "RecordFileChangedContext",
	"obs:obs:replay-buffer:replay-buffer-started": "OutputStateContext",
	"obs:obs:virtual-cam:virtual-camera-started": "OutputStateContext",
	"obs:obs:studio-mode:studio-mode-enabled": "StudioModeContext",
	"stream-deck:stream-deck:key-down": "StreamDeckEventContext",
	"twitch:twitch:chat:chat-message": "ChatMessageContext",
	"twitch:twitch:chat:cheer": "CheerContext",
	"twitch:twitch:chat:whisper": "WhisperContext",
	"twitch:twitch:chat:channel-point-redemption": "RedemptionContext",
	"twitch:twitch:chat:hype-chat": "HypeChatContext",
	"twitch:twitch:subscriptions:new-subscription": "SubContext",
	"twitch:twitch:subscriptions:resubscription": "SubContext",
	"twitch:twitch:subscriptions:gift-subscription": "GiftSubContext",
	"twitch:twitch:subscriptions:community-subscription": "CommunitySubContext",
	"twitch:twitch:raids:incoming-raid": "RaidContext",
	"twitch:twitch:moderation:user-banned": "ModerationContext",
	"twitch:twitch:moderation:user-timed-out": "ModerationContext",
	"twitch:twitch:moderation:user-banned-eventsub": "EventSubModerationContext",
	"twitch:twitch:moderation:user-unbanned-eventsub": "EventSubModerationContext",
	"twitch:twitch:moderation:shield-mode-enabled": "EventSubModerationContext",
	"twitch:twitch:moderation:shield-mode-disabled": "EventSubModerationContext",
	"twitch:twitch:engagement:user-join": "UserJoinPartContext",
	"twitch:twitch:engagement:user-part": "UserJoinPartContext",
	"twitch:twitch:stream:stream-online": "StreamContext",
	"twitch:twitch:stream:stream-offline": "StreamContext",
	"twitch:twitch:channel:new-follower": "FollowContext",
	"twitch:twitch:channel:channel-update": "ChannelUpdateContext",
	"twitch:twitch:channel-points:reward-redeemed": "PointsRedemptionContext",
	"twitch:twitch:hype-train:hype-train-begin": "HypeTrainContext",
	"twitch:twitch:hype-train:hype-train-progress": "HypeTrainContext",
	"twitch:twitch:hype-train:hype-train-end": "HypeTrainContext",
	"twitch:twitch:polls:poll-begin": "PollContext",
	"twitch:twitch:polls:poll-end": "PollContext",
	"twitch:twitch:predictions:prediction-begin": "PredictionContext",
	"twitch:twitch:predictions:prediction-lock": "PredictionContext",
	"twitch:twitch:predictions:prediction-end": "PredictionContext",
	"twitch:twitch:goals:goal-begin": "GoalContext",
	"twitch:twitch:goals:goal-progress": "GoalContext",
	"twitch:twitch:goals:goal-end": "GoalContext",
	"twitch:twitch:charity:charity-campaign-start": "CharityContext",
	"twitch:twitch:charity:charity-campaign-progress": "CharityContext",
	"twitch:twitch:charity:charity-campaign-stop": "CharityContext",
	"twitch:twitch:charity:charity-donation": "CharityContext",
	"twitch:twitch:ads:ad-break-begin": "AdBreakContext",
	"twitch:twitch:shoutouts:shoutout-received": "ShoutoutReceivedContext",
	"websocket:websocket:message-received": "WsMessageContext",
	"websocket:websocket:connected": "WsConnectionStateContext",
	"websocket:websocket:disconnected": "WsConnectionStateContext",
	"youtube:youtube:chat:chat-message": "ChatMessageContext",
	"youtube:youtube:chat:super-chat": "SuperChatContext",
	"youtube:youtube:chat:super-sticker": "SuperStickerContext",
	"youtube:youtube:chat:gift-jewels": "GiftContext",
	"youtube:youtube:chat:live-poll": "PollContext",
	"youtube:youtube:chat:members-only-mode-started": "SponsorsOnlyContext",
	"youtube:youtube:membership:new-member": "NewMemberContext",
	"youtube:youtube:membership:member-milestone": "MemberMilestoneContext",
	"youtube:youtube:membership:membership-gift": "MembershipGiftContext",
	"youtube:youtube:membership:gift-membership-received": "GiftMembershipReceivedContext",
	"youtube:youtube:moderation:user-banned": "ModerationContext",
	"youtube:youtube:moderation:message-deleted": "MessageDeletedContext",
	"youtube:youtube:stream:stream-online": "StreamContext",
	"youtube:youtube:stream:stream-offline": "StreamContext",
	"overlay:overlay:message:message-received": "OverlayMessageContext"
} as const;
