// AUTO-GENERATED by packages/app/scripts/build-plugin-host.mjs — do not edit.
export declare const PLUGIN_HOST_UI_SUBPATHS: readonly 'alert' | 'attachments' | 'badge' | 'blocks' | 'button' | 'container' | 'dropdown' | 'heading' | 'input' | 'log-viewer' | 'logo' | 'nav' | 'popover' | 'scroll-area' | 'tooltip' | 'variable-popover'[];

export declare const PLUGIN_HOST_SVELTE_SUBPATHS: readonly 'internal/disclose-version' | 'internal/client' | 'reactivity';
