import type { editor } from 'monaco-editor';

export const streamKitMonacoTheme: editor.IStandaloneThemeData = {
	base: 'vs-dark',
	inherit: true,
	rules: [
		{ token: 'comment', foreground: '6b7280', fontStyle: 'italic' },
		{ token: 'keyword', foreground: 'c084fc' },
		{ token: 'string', foreground: '86efac' },
		{ token: 'number', foreground: 'fbbf24' },
		{ token: 'type', foreground: '67e8f9' },
		{ token: 'identifier', foreground: 'e5e7eb' }
	],
	colors: {
		'editor.background': '#111827',
		'editor.foreground': '#e5e7eb',
		'editorLineNumber.foreground': '#4b5563',
		'editorLineNumber.activeForeground': '#9ca3af',
		'editor.selectionBackground': '#374151',
		'editor.inactiveSelectionBackground': '#1f2937',
		'editorCursor.foreground': '#a78bfa',
		'editor.lineHighlightBackground': '#1f293780',
		'editorIndentGuide.background': '#374151',
		'editorIndentGuide.activeBackground': '#4b5563',
		'editorWidget.background': '#111827',
		'editorWidget.foreground': '#e5e7eb',
		'editorWidget.border': '#374151',
		'editorHoverWidget.background': '#111827',
		'editorHoverWidget.foreground': '#e5e7eb',
		'editorHoverWidget.border': '#374151',
		'editorSuggestWidget.background': '#111827',
		'editorSuggestWidget.foreground': '#e5e7eb',
		'editorSuggestWidget.border': '#374151',
		'editorSuggestWidget.selectedBackground': '#1f2937',
		'editorSuggestWidget.selectedForeground': '#f9fafb',
		'editorSuggestWidget.highlightForeground': '#c084fc',
		'editorSuggestWidget.focusHighlightForeground': '#c084fc',
		'menu.background': '#111827',
		'menu.foreground': '#e5e7eb',
		'menu.border': '#374151',
		'menu.selectionBackground': '#1f2937',
		'menu.selectionForeground': '#f9fafb',
		'menu.separatorBackground': '#374151',
		'editorActionList.background': '#111827',
		'editorActionList.foreground': '#e5e7eb',
		'editorActionList.focusBackground': '#1f2937',
		'editorActionList.focusForeground': '#f9fafb',
		'input.background': '#1f2937',
		'input.foreground': '#e5e7eb',
		'input.border': '#374151',
		'quickInput.background': '#111827',
		'quickInput.foreground': '#e5e7eb'
	}
};
